version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j-knowledge-graph
    environment:
      - NEO4J_AUTH=neo4j/knowledge123  # username/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2g
    ports:
      - "7474:7474"  # Neo4j Browser (Web UI)
      - "7687:7687"  # Bolt protocol for drivers
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs: